name: Update parappally/README.md with new joke on issue

on:
  issues:
    types: [opened]

jobs:

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'joke')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set environment variables
        run: | 
          echo ::set-env name=ISSUE_USER_LOGIN::${{ github.event.issue.user.login }} 

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python script
        run: |
          python scripts/update.py

      - name: setup git config
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}

      - name: commit changes
        run: |
          chmod +x ./scripts/commit.sh
          ./scripts/commit.sh
