name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: parappally/parappally@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
